name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'docs'

env:
  BUILDER_VERSION: v0.9.35
  BUILDER_SOURCE: releases
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-crt-python
  LINUX_BASE_IMAGE: ubuntu-18-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  AWS_REGION: us-east-1

jobs:
  openbsd:
    runs-on: ubuntu-latest # macos would be faster. TODO: diagnose why some tests are failing
    timeout-minutes: 30
    steps:
      - name: Build ${{ env.PACKAGE_NAME }} + consumers
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.2'
          shell: bash
          environment_variables: AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION AWS_REGION
          run: |
            sudo pkg_add -v awscli py3-pip py3-urllib3
            pkg_info
            python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz', 'builder')"
            chmod a+x builder
            ./builder build -p ${{ env.PACKAGE_NAME }}

